### PR TITLE
refactor: use std::vector instead of bespoke Array class

### LINKED ISSUE #6: Member access within misaligned address for type 'UTPSocketKeyData', which requires 8 byte alignment
### What is the issue?

Undefined Behavior Runtime error in libutp, on that line:
https://github.com/transmission/libutp/blob/c95738b1a6644b919e5b64d3ea9736cfc5894e0b/utp_internal.cpp#L2574
>Thread 6: Misaligned pointer use
>Member access within misaligned address 0x0001570734ec for type 'UTPSocketKeyData', which requires 8 byte alignment

It's not a crash, but as it says, it's undefined behavior.
The Xcode documentation to attempt to resolve that is at https://developer.apple.com/documentation/xcode/misaligned-pointer.

Historically, that piece of code is from 2013 (https://github.com/transmission/libutp/commit/365254427e5358a0c390aa5a60df5f449b9c0f00). We kind of branched off libutp from a commit of July 2017 (https://github.com/transmission/libutp/tree/d7daf7f36f64da975fc1b42772f774cbd5ffbbf1), but the official bittorrent repo has been abandoned since then, so no one else is maintaining libutp officially. I still opened an issue at https://github.com/bittorrent/libutp/issues/136 some time ago.

Capture d’écran 2023-06-18 à 00 21 02

```
Thread 6#0	0x0000000104f08eb4 in __ubsan_on_report ()
#1	0x0000000104f08f68 in __ubsan::UndefinedBehaviorReport::UndefinedBehaviorReport(char const*, __ubsan::Location&, __sanitizer::InternalScopedString&) ()
#2	0x0000000104f048f8 in __ubsan::Diag::~Diag() ()
#3	0x0000000104f06234 in handleTypeMismatchImpl(__ubsan::TypeMismatchData*, unsigned long, __ubsan::ReportOptions) ()
#4	0x0000000104f05ebc in __ubsan_handle_type_mismatch_v1 ()
#5	0x00000001033a44d8 in utp_initialize_socket(UTPSocket*, sockaddr const*, unsigned int, bool, unsigned int, unsigned int, unsigned int) at /Users/User/Developer/transmission/third-party/libutp/utp_internal.cpp:2574
#6	0x00000001033a7cfc in ::utp_connect(utp_socket *, const sockaddr *, socklen_t) at /Users/User/Developer/transmission/third-party/libutp/utp_internal.cpp:2748
#7	0x0000000102bcbfe8 in tr_peerIo::new_outgoing(tr_session*, tr_bandwidth*, tr_address const&, tr_port, std::__1::array<std::byte, 20ul> const&, bool, bool) at /Users/User/Developer/transmission/libtransmission/peer-io.cc:142
#8	0x0000000102bf647c in (anonymous namespace)::connect_helpers::initiateConnection(tr_peerMgr*, tr_swarm*, peer_atom&) at /Users/User/Developer/transmission/libtransmission/peer-mgr.cc:2451
#9	0x0000000102bf3608 in tr_peerMgr::makeNewPeerConnections(unsigned long) at /Users/User/Developer/transmission/libtransmission/peer-mgr.cc:2490
#10	0x0000000102bf2598 in tr_peerMgr::reconnectPulse() at /Users/User/Developer/transmission/libtransmission/peer-mgr.cc:2156
#11	0x0000000102bf39b8 in tr_peerMgr::bandwidthPulse() at /Users/User/Developer/transmission/libtransmission/peer-mgr.cc:2221
#12	0x0000000102bfeac4 in tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()::operator()() const at /Users/User/Developer/transmission/libtransmission/peer-mgr.cc:689
#13	0x0000000102bfea6c in decltype(std::declval<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&>()()) std::__1::__invoke[abi:v160002]<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&>(tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&) at /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__functional/invoke.h:394
#14	0x0000000102bfe8dc in void std::__1::__invoke_void_return_wrapper<void, true>::__call<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&>(tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&) at /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__functional/invoke.h:487
#15	0x0000000102bfe870 in std::__1::__function::__alloc_func<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'(), std::__1::allocator<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()>, void ()>::operator()[abi:v160002]() at /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__functional/function.h:185
#16	0x0000000102bfa778 in std::__1::__function::__func<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'(), std::__1::allocator<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()>, void ()>::operator()() at /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__functional/function.h:356
#17	0x0000000102b81754 in std::__1::__function::__value_func<void ()>::operator()[abi:v160002]() const at /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__functional/function.h:510
#18	0x0000000102b7ff90 in std::__1::function<void ()>::operator()() const at /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__functional/function.h:1156
#19	0x00000001030e0ab0 in libtransmission::EvTimer::handleTimer() at /Users/User/Developer/transmission/libtransmission/timer-ev.cc:145
#20	0x00000001030dfd40 in libtransmission::EvTimer::onTimer(int, short, void*) at /Users/User/Developer/transmission/libtransmission/timer-ev.cc:137
#21	0x0000000103286868 in event_persist_closure at /Users/User/Developer/transmission/third-party/libevent/event.c:1623
#22	0x000000010328255c in event_process_active_single_queue at /Users/User/Developer/transmission/third-party/libevent/event.c:1682
#23	0x00000001032621d8 in event_process_active at /Users/User/Developer/transmission/third-party/libevent/event.c:1783
#24	0x000000010325b600 in event_base_loop at /Users/User/Developer/transmission/third-party/libevent/event.c:2006
#25	0x0000000102b7e790 in tr_session_thread_impl::sessionThreadFunc(event_base*) at /Users/User/Developer/transmission/libtransmission/session-thread.cc:245
#26	0x0000000102b83980 in decltype(*std::declval<tr_session_thread_impl*>().*std::declval<void (tr_session_thread_impl::*)(event_base*)>()(std::declval<event_base*>())) std::__1::__invoke[abi:v160002]<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, void>(void (tr_session_thread_impl::*&&)(event_base*), tr_session_thread_impl*&&, event_base*&&) at /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__functional/invoke.h:359
#27	0x0000000102b838ac in void std::__1::__thread_execute[abi:v160002]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, 2ul, 3ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>&, std::__1::__tuple_indices<2ul, 3ul>) at /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/thread:288
#28	0x0000000102b82770 in void* std::__1::__thread_proxy[abi:v160002]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>>(void*) at /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/thread:299
#29	0x0000000104b61628 in _pthread_start ()
```

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.1.0-dev (76166d8fa7)

### PR DESCRIPTION
**Pull request by ckerr**
Part one of a three-part series to use `std::` tools instead of bespoke ones.  Part three will fix https://github.com/transmission/libutp/issues/6.

- [x] Part 1: #7
- [x] Part 2: #12
- [x] Part 3: #13

Unfortunately there don't seem to be any real tests for libutp, so the need to manually test is even greater than usual.

### CODE REVIEW

**Comment by ckerr** [comment]
@tearfur also requesting review from you since you've been so active in the C++ code lately, but GitHub doesn't give me that option in the Reviewers list.

Possibly it only shows people who have been previously active in the repo :thinking: Along that same rationale, I'm not sure if @'ing you here will show up in your notifications. I guess if you don't pong here I'll ping you in another PR instead :smile_cat:

**Review by mikedld — APPROVED** [review]

**Review by tearfur — APPROVED** [review]

**Comment by mikedld** [comment]
> Unfortunately there don't seem to be any real tests for libutp, so the need to manually test is even greater than usual.

If we're forking it for good, might make sense to pull bittorrent/libutp#127 so that we're not completely blind here.

**Comment by ckerr** [comment]
> might make sense to pull https://github.com/bittorrent/libutp/pull/127 so that we're not completely blind here

Agreed. @mikedld Can you copy libutp/pull/127 into a PR in this repo?

> If we're forking it for good

The last upstream commit was six years ago; but even so, forking isn't my first choice.

Looks like the last maintainer comment in a PR was in 2019; however, it was by @arvidn who is still very active on libtorrent, so maybe there's hope. Arvid, do you have any thoughts on landing PRs in https://github.com/bittorrent/libutp?

@mikedld IMO even *if* we fork we should keep changes compatible w/upstream and try to upstream them, e.g. PRs like https://github.com/bittorrent/libutp/pull/132 or this one, e.g. housekeeping & small fixes, not big changes or protocol changes.

**Comment by mikedld** [comment]
It's already there in `post-3.4-transmission` branch, although uses CMake and not platform-specific build configs. Anyway, #8 is the slightly updated version of the upstream PR.

**Comment by mikedld** [comment]
If it's not the fork-fork yet, did you mean to target `post-3.4-transmission` with this PR then? Otherwise, should probably merge `post-3.4-transmission` changes into `master`...

**Comment by ckerr** [comment]
@mikedld, agreed. I've updated the branch to target `post-3.4-transmission`

**Comment by mikedld** [comment]
@ckerr, CI seems to be unhappy with C++ standard now, need to adjust the default in https://github.com/transmission/libutp/blob/8bdf5e84d6e794a3d72f4b91ddddd1625175207e/CMakeLists.txt#L27

**Review by mikedld — APPROVED** [review]

**Comment by tearfur** [comment]
@ckerr @mikedld ping

**Comment by mikedld** [comment]
I'm fine with it, was under the impression that @ckerr is waiting out for something or maybe doing some more testing.

**Comment by ckerr** [comment]
I guess I've been holding back on this PR because it really belongs upstream.

As mentioned above, there are a couple of followups to this. I hope all of them make it upstream someday -- I'm not going to make any big breaking changes.

**Comment by ckerr** [comment]
https://github.com/transmission/libutp/pull/10

**Pull request merged**
